#!/bin/bash

C3BASEPATH=$( [[ "$(uname -s)" == Darwin ]] && echo "$HOME/open-c3-workspace" || echo "/data" )

cd $C3BASEPATH/open-c3 || exit

find Connector/tt/trouble-ticketing/ -name "*.go" |grep -v /tmp/pkg/mod/
