#!/bin/bash

C3BASEPATH=$(case  $(uname -s) in Darwin*) echo "$HOME/open-c3-workspace";; *) echo "/data";; esac)

cd $C3BASEPATH/open-c3 || exit

find Connector/tt/trouble-ticketing/ -name "*.go" |grep -v /tmp/pkg/mod/
