#!/bin/bash
set -e

C3BASEPATH=$( [[ "$(uname -s)" == Darwin ]] && echo "$HOME/open-c3-workspace" || echo "/data" )

cd $C3BASEPATH/open-c3 || exit

find */lib/api/ -name *pm
find Connector/pp -name "c3mc-*"

find . -name "*.md"|grep -v /node_modules/|grep -v /bower_components/|grep -v /mod/ |sed 's/^\.\///'
